"""initial schema

Revision ID: 9385218a2ea3
Revises: 
Create Date: 2026-08-25 12:17:18.429698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9385218a2ea3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_chapter_id'), 'analysis_tasks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_created_at'), 'analysis_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_project_id'), 'analysis_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_user_id'), 'analysis_tasks', ['user_id'], unique=False)
    op.create_table('goal_stability_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scan_round', sa.String(length=36), nullable=True),
    sa.Column('original_goal', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('fix_action', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('drift_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_stability_log_goal_id'), 'goal_stability_log', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_stability_log_project_id'), 'goal_stability_log', ['project_id'], unique=False)
    op.create_table('golden_fingers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='所属项目ID'),
    sa.Column('character_id', sa.String(length=36), nullable=True, comment='关联角色ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='金手指名称'),
    sa.Column('appearance', sa.Text(), nullable=True, comment='表现形式'),
    sa.Column('personality_consciousness', sa.Text(), nullable=True, comment='性格/意识'),
    sa.Column('core_functions', sa.Text(), nullable=True, comment='核心功能'),
    sa.Column('energy_consumption', sa.Text(), nullable=True, comment='能量消耗'),
    sa.Column('limitations_costs', sa.Text(), nullable=True, comment='限制/代价'),
    sa.Column('background', sa.Text(), nullable=True, comment='背景故事'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('traits', sa.Text(), nullable=True, comment='特性标签'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_fingers_project_id'), 'golden_fingers', ['project_id'], unique=False)
    op.create_table('mistake_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='项目ID'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='用户ID'),
    sa.Column('audit_log_id', sa.String(length=36), nullable=True, comment='关联的 CommandAuditLog ID'),
    sa.Column('command_name', sa.String(length=64), nullable=False, comment='失败的命令名称'),
    sa.Column('error_type', sa.String(length=64), nullable=True, comment='错误分类: unknown_command/execution_error/validation_error/timeout/permission'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='原始错误信息'),
    sa.Column('params', sa.JSON(), nullable=True, comment='命令参数 (JSON)'),
    sa.Column('root_cause', sa.String(length=500), nullable=True, comment='自动推断的根因'),
    sa.Column('solution', sa.String(length=500), nullable=True, comment='建议的解决方案'),
    sa.Column('frequency', sa.Integer(), nullable=True, comment='同类错误累计次数'),
    sa.Column('resolved', sa.Integer(), nullable=True, comment='是否已修复 0/1'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='修复时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='错误发生时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistake_logs_command_name'), 'mistake_logs', ['command_name'], unique=False)
    op.create_index(op.f('ix_mistake_logs_error_type'), 'mistake_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_mistake_logs_project_id'), 'mistake_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_mistake_logs_user_id'), 'mistake_logs', ['user_id'], unique=False)
    op.create_table('narrative_structure_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('node_type', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('pov_character_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_structure_nodes_project_id'), 'narrative_structure_nodes', ['project_id'], unique=False)
    op.create_table('pm_action_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='调用的工具名'),
    sa.Column('table_name', sa.String(length=50), nullable=True, comment='操作的数据库表'),
    sa.Column('target_id', sa.String(length=36), nullable=True, comment='操作对象的主键ID'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='目标类型：chapter/character/foreshadow...'),
    sa.Column('snapshot_before', sa.JSON(), nullable=True, comment='操作前的完整状态快照'),
    sa.Column('snapshot_after', sa.JSON(), nullable=True, comment='操作后的状态（用于验证）'),
    sa.Column('params_json', sa.Text(), nullable=True, comment='原始调用参数（JSON）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_pm_action_log_project_id'), 'pm_action_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_action_log_tool_name'), 'pm_action_log', ['tool_name'], unique=False)
    op.create_index(op.f('ix_pm_action_log_user_id'), 'pm_action_log', ['user_id'], unique=False)
    op.create_table('pm_autonomy_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False, comment='advisor | advisor_plus | autonomous'),
    sa.Column('confidence_threshold', sa.Float(), nullable=False, comment='>threshold 自动执行，<threshold 询问用户'),
    sa.Column('auto_execute_types', sa.String(length=500), nullable=False, comment='允许自动执行的工具类型'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_autonomy_config_project_id'), 'pm_autonomy_config', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_autonomy_config_user_id'), 'pm_autonomy_config', ['user_id'], unique=False)
    op.create_table('pm_decision_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('diag_type', sa.String(length=50), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('original_message', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('fix_action', sa.Text(), nullable=True),
    sa.Column('fix_result', sa.String(length=20), nullable=True),
    sa.Column('fix_attempted', sa.Boolean(), nullable=True),
    sa.Column('fix_details', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verify_message', sa.Text(), nullable=True),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('original_score', sa.Integer(), nullable=True),
    sa.Column('post_fix_score', sa.Integer(), nullable=True),
    sa.Column('score_delta', sa.Integer(), nullable=True),
    sa.Column('scan_round', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pm_decision_project_created', 'pm_decision_log', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_pm_decision_resolved', 'pm_decision_log', ['project_id', 'verified'], unique=False)
    op.create_index(op.f('ix_pm_decision_log_created_at'), 'pm_decision_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_pm_decision_log_project_id'), 'pm_decision_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_decision_log_user_id'), 'pm_decision_log', ['user_id'], unique=False)
    op.create_table('pm_diagnostic_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('diag_type', sa.String(length=50), nullable=False, comment='类型：foreshadow_overdue/consistency_issue/style_drift/chapter_quality/pov_issue/arc_incomplete/relationship_gap/other'),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='warning / critical'),
    sa.Column('message', sa.String(length=500), nullable=False, comment='诊断摘要'),
    sa.Column('suggestion', sa.String(length=500), nullable=True, comment='修复建议'),
    sa.Column('chapter_number', sa.Integer(), nullable=True, comment='涉及章节号'),
    sa.Column('character_id', sa.String(length=36), nullable=True, comment='涉及角色ID'),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('resolved_by', sa.String(length=100), nullable=True, comment='处理方式：auto_fix/manual'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diag_project', 'pm_diagnostic_logs', ['project_id'], unique=False)
    op.create_index('idx_diag_resolved', 'pm_diagnostic_logs', ['resolved'], unique=False)
    op.create_index('idx_diag_type', 'pm_diagnostic_logs', ['diag_type'], unique=False)
    op.create_index('idx_diag_user', 'pm_diagnostic_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_pm_diagnostic_logs_diag_type'), 'pm_diagnostic_logs', ['diag_type'], unique=False)
    op.create_index(op.f('ix_pm_diagnostic_logs_project_id'), 'pm_diagnostic_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_diagnostic_logs_resolved'), 'pm_diagnostic_logs', ['resolved'], unique=False)
    op.create_index(op.f('ix_pm_diagnostic_logs_user_id'), 'pm_diagnostic_logs', ['user_id'], unique=False)
    op.create_table('pm_experience_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型: fusion/smoothing/review'),
    sa.Column('pattern', sa.Text(), nullable=True, comment='模式描述（提炼的经验）'),
    sa.Column('success_conditions', sa.Text(), nullable=True, comment='成功条件'),
    sa.Column('context_patterns', sa.JSON(), nullable=True, comment='适用场景特征'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('success_rate', sa.Float(), nullable=True, comment='成功率'),
    sa.Column('source_scores', sa.JSON(), nullable=True, comment='来源案例的评分详情'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_experience_cards_project_id'), 'pm_experience_cards', ['project_id'], unique=False)
    op.create_table('pm_failure_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False, comment='模式类型: ooc/inconsistency/pace/hook'),
    sa.Column('error_description', sa.Text(), nullable=True, comment='错误描述'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='根因分析'),
    sa.Column('recovery_suggestion', sa.Text(), nullable=True, comment='恢复/修复建议'),
    sa.Column('occurrence_count', sa.Integer(), nullable=True, comment='出现次数'),
    sa.Column('last_occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_failure_patterns_project_id'), 'pm_failure_patterns', ['project_id'], unique=False)
    op.create_table('pm_fix_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('pattern_text', sa.Text(), nullable=True),
    sa.Column('source_decision_id', sa.String(length=36), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fix_pattern_type_created', 'pm_fix_patterns', ['issue_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_pm_fix_patterns_issue_type'), 'pm_fix_patterns', ['issue_type'], unique=False)
    op.create_table('pm_goal_tree',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='null=根目标'),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('goal_text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending / in_progress / done / abandoned'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1-5，5最高'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_goal_tree_goal_id'), 'pm_goal_tree', ['goal_id'], unique=True)
    op.create_index(op.f('ix_pm_goal_tree_parent_id'), 'pm_goal_tree', ['parent_id'], unique=False)
    op.create_index(op.f('ix_pm_goal_tree_project_id'), 'pm_goal_tree', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_goal_tree_user_id'), 'pm_goal_tree', ['user_id'], unique=False)
    op.create_table('pm_guidance_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_log_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_guidance_fb_type_created', 'pm_guidance_feedback', ['issue_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_pm_guidance_feedback_decision_log_id'), 'pm_guidance_feedback', ['decision_log_id'], unique=False)
    op.create_table('pm_history_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('pattern_type', sa.String(length=32), nullable=False, comment='tool_sequence / goal_pattern / topic_pattern'),
    sa.Column('pattern_data', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_history_patterns_project_id'), 'pm_history_patterns', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_history_patterns_user_id'), 'pm_history_patterns', ['user_id'], unique=False)
    op.create_table('pm_leader_lock',
    sa.Column('lock_name', sa.String(length=50), nullable=False),
    sa.Column('holder_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lock_name')
    )
    op.create_table('pm_session_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('last_action', sa.String(length=500), nullable=True, comment='上次操作的文字描述'),
    sa.Column('last_tool', sa.String(length=100), nullable=True, comment='上次调用的工具名'),
    sa.Column('last_chapter_id', sa.String(length=36), nullable=True, comment='关联的章节ID'),
    sa.Column('pending_goals', sa.JSON(), nullable=False, comment='未完成的goals列表'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='上次操作的成功置信度 0-1'),
    sa.Column('extra_data', sa.JSON(), nullable=False, comment='扩展数据：quality_forecast / self_tuning 等'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_session_state_project_id'), 'pm_session_state', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_session_state_user_id'), 'pm_session_state', ['user_id'], unique=False)
    op.create_table('pm_token_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('cost_usd', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pm_token_project_created', 'pm_token_usage', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_pm_token_user_created', 'pm_token_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pm_token_usage_created_at'), 'pm_token_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_pm_token_usage_project_id'), 'pm_token_usage', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_token_usage_user_id'), 'pm_token_usage', ['user_id'], unique=False)
    op.create_table('pm_user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('preference_type', sa.String(length=50), nullable=False, comment='偏好类型: pacing/dialogue/description'),
    sa.Column('value', sa.JSON(), nullable=True, comment='偏好值'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='置信度 0-1'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='来源: feedback/edit/review'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_user_preferences_project_id'), 'pm_user_preferences', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_user_preferences_user_id'), 'pm_user_preferences', ['user_id'], unique=False)
    op.create_table('pm_user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False, comment='beginner / intermediate / expert'),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('avg_session_chars', sa.Integer(), nullable=False, comment='平均每 session 输入字数'),
    sa.Column('skills_mastered', sa.JSON(), nullable=False, comment='已熟练使用的 skill 名称列表'),
    sa.Column('preferred_detail_level', sa.String(length=10), nullable=False, comment='high / medium / low'),
    sa.Column('detail_prompt_hint', sa.String(length=200), nullable=True, comment='系统 prompt 中使用的语气提示'),
    sa.Column('recent_tool_diversity', sa.Integer(), nullable=False, comment='最近10次对话用过的不同工具数'),
    sa.Column('last_question_type', sa.String(length=20), nullable=True, comment='上次对话的问题类型: beginner/intermediate/expert'),
    sa.Column('question_type_counts', sa.JSON(), nullable=False, comment='各问题类型计数: {"beginner":0,"intermediate":0,"expert":0}'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_user_profiles_user_id'), 'pm_user_profiles', ['user_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='项目标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目简介'),
    sa.Column('theme', sa.Text(), nullable=True, comment='主题'),
    sa.Column('genre', sa.String(length=50), nullable=True, comment='小说类型'),
    sa.Column('target_words', sa.Integer(), nullable=True, comment='目标字数'),
    sa.Column('current_words', sa.Integer(), nullable=True, comment='当前字数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='创作状态'),
    sa.Column('wizard_status', sa.String(length=20), nullable=True, comment='向导完成状态: incomplete/completed'),
    sa.Column('wizard_step', sa.Integer(), nullable=True, comment='向导当前步骤: 0-4'),
    sa.Column('outline_mode', sa.String(length=20), nullable=False, comment='大纲章节模式: one-to-one(传统模式) 或 one-to-many(细化模式)'),
    sa.Column('world_time_period', sa.Text(), nullable=True, comment='时间背景'),
    sa.Column('world_location', sa.Text(), nullable=True, comment='地理位置'),
    sa.Column('world_atmosphere', sa.Text(), nullable=True, comment='氛围基调'),
    sa.Column('world_rules', sa.Text(), nullable=True, comment='世界规则'),
    sa.Column('chapter_count', sa.Integer(), nullable=True, comment='章节数量'),
    sa.Column('narrative_perspective', sa.String(length=50), nullable=True, comment='叙事视角：first_person/third_person/omniscient'),
    sa.Column('character_count', sa.Integer(), nullable=True, comment='角色数量'),
    sa.Column('cover_image_url', sa.String(length=1000), nullable=True, comment='封面图片访问地址'),
    sa.Column('cover_prompt', sa.Text(), nullable=True, comment='最近一次生成封面使用的提示词'),
    sa.Column('cover_status', sa.String(length=20), nullable=False, comment='封面状态: none/generating/ready/failed'),
    sa.Column('cover_error', sa.Text(), nullable=True, comment='最近一次封面生成失败原因'),
    sa.Column('cover_updated_at', sa.DateTime(), nullable=True, comment='最近一次封面生成成功时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.CheckConstraint("cover_status IN ('none', 'generating', 'ready', 'failed')", name='check_cover_status'),
    sa.CheckConstraint("outline_mode IN ('one-to-one', 'one-to-many')", name='check_outline_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('api_provider', sa.String(length=50), nullable=True, comment='API提供商'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='API密钥'),
    sa.Column('api_base_url', sa.String(length=500), nullable=True, comment='自定义API地址'),
    sa.Column('llm_model', sa.String(length=100), nullable=True, comment='模型名称'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='温度参数'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大token数'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统级别提示词，每次AI调用都会使用'),
    sa.Column('cover_api_provider', sa.String(length=50), nullable=True, comment='封面图片API提供商'),
    sa.Column('cover_api_key', sa.String(length=500), nullable=True, comment='封面图片API密钥'),
    sa.Column('cover_api_base_url', sa.String(length=500), nullable=True, comment='封面图片自定义API地址'),
    sa.Column('cover_image_model', sa.String(length=100), nullable=True, comment='封面图片模型名称'),
    sa.Column('cover_enabled', sa.Boolean(), server_default='0', nullable=False, comment='是否启用封面图片生成'),
    sa.Column('smtp_provider', sa.String(length=50), server_default='qq', nullable=False, comment='SMTP 提供商'),
    sa.Column('smtp_host', sa.String(length=255), nullable=True, comment='SMTP 主机'),
    sa.Column('smtp_port', sa.Integer(), server_default='465', nullable=False, comment='SMTP 端口'),
    sa.Column('smtp_username', sa.String(length=255), nullable=True, comment='SMTP 用户名'),
    sa.Column('smtp_password', sa.String(length=500), nullable=True, comment='SMTP 密码或授权码'),
    sa.Column('smtp_use_tls', sa.Boolean(), server_default='0', nullable=False, comment='是否启用 TLS'),
    sa.Column('smtp_use_ssl', sa.Boolean(), server_default='1', nullable=False, comment='是否启用 SSL'),
    sa.Column('smtp_from_email', sa.String(length=255), nullable=True, comment='发件人邮箱'),
    sa.Column('smtp_from_name', sa.String(length=255), server_default='WLAINovel', nullable=False, comment='发件人名称'),
    sa.Column('email_auth_enabled', sa.Boolean(), server_default='1', nullable=False, comment='是否启用邮箱认证'),
    sa.Column('email_register_enabled', sa.Boolean(), server_default='1', nullable=False, comment='是否启用邮箱注册'),
    sa.Column('verification_code_ttl_minutes', sa.Integer(), server_default='10', nullable=False, comment='验证码有效期（分钟）'),
    sa.Column('verification_resend_interval_seconds', sa.Integer(), server_default='60', nullable=False, comment='验证码重发间隔（秒）'),
    sa.Column('preferences', sa.Text(), nullable=True, comment='其他偏好设置(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_id', 'settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    op.create_table('character_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('character_from_id', sa.String(length=36), nullable=False),
    sa.Column('character_to_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_name', sa.String(length=50), nullable=True),
    sa.Column('intimacy_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_char_rels_from_to', 'character_relationships', ['project_id', 'character_from_id', 'character_to_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_character_from_id'), 'character_relationships', ['character_from_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_character_to_id'), 'character_relationships', ['character_to_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_project_id'), 'character_relationships', ['project_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色/组织名称'),
    sa.Column('age', sa.String(length=50), nullable=True, comment='年龄'),
    sa.Column('gender', sa.String(length=50), nullable=True, comment='性别'),
    sa.Column('is_organization', sa.Boolean(), nullable=True, comment='是否为组织'),
    sa.Column('role_type', sa.String(length=50), nullable=True, comment='角色类型'),
    sa.Column('personality', sa.Text(), nullable=True, comment='性格特点/组织特性'),
    sa.Column('speaking_style', sa.Text(), nullable=True, comment='说话风格/语气特点'),
    sa.Column('speech_patterns', sa.Text(), nullable=True, comment='说话模式：语气词、口头禅、断句特点等结构化描述'),
    sa.Column('background', sa.Text(), nullable=True, comment='背景故事'),
    sa.Column('appearance', sa.Text(), nullable=True, comment='外貌描述'),
    sa.Column('relationships', sa.Text(), nullable=True, comment='人物关系(JSON)'),
    sa.Column('organization_type', sa.String(length=100), nullable=True, comment='组织类型'),
    sa.Column('organization_purpose', sa.String(length=500), nullable=True, comment='组织目的'),
    sa.Column('organization_members', sa.Text(), nullable=True, comment='组织成员(JSON)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/deceased/missing/retired/destroyed'),
    sa.Column('status_changed_chapter', sa.Integer(), nullable=True, comment='状态变更的章节号'),
    sa.Column('current_state', sa.Text(), nullable=True, comment='角色当前心理状态（由分析自动更新）'),
    sa.Column('state_updated_chapter', sa.Integer(), nullable=True, comment='心理状态最后更新的章节号'),
    sa.Column('main_career_id', sa.String(length=36), nullable=True, comment='主职业ID'),
    sa.Column('main_career_stage', sa.Integer(), nullable=True, comment='主职业当前阶段'),
    sa.Column('sub_careers', sa.Text(), nullable=True, comment='副职业列表(JSON): [{"career_id": "xxx", "stage": 3}, ...]'),
    sa.Column('screen_time_weight', sa.Float(), nullable=True, comment='戏份权重(0.0~1.0)'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('traits', sa.Text(), nullable=True, comment='特征标签(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_project', 'characters', ['project_id'], unique=False)
    op.create_index('idx_character_role', 'characters', ['project_id', 'role_type'], unique=False)
    op.create_table('ooc_violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ooc_violations_chapter_id'), 'ooc_violations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_ooc_violations_character_id'), 'ooc_violations', ['character_id'], unique=False)
    op.create_index(op.f('ix_ooc_violations_created_at'), 'ooc_violations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ooc_violations_project_id'), 'ooc_violations', ['project_id'], unique=False)
    op.create_index('ix_ooc_violations_project_status', 'ooc_violations', ['project_id', 'status'], unique=False)
    op.create_table('outlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='大纲标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='大纲内容'),
    sa.Column('structure', sa.Text(), nullable=True, comment='结构化大纲数据(JSON)，使用OutlineStructure schema'),
    sa.Column('order_index', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outline_project', 'outlines', ['project_id'], unique=False)
    op.create_table('pm_session_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('summary_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_session_summaries_project_id'), 'pm_session_summaries', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_session_summaries_session_id'), 'pm_session_summaries', ['session_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('skill_type', sa.String(length=20), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('review_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='故事线名称'),
    sa.Column('line_type', sa.String(length=50), nullable=False, comment='线类型: main/sub/hidden/romance'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/dormant/completed/abandoned'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='显示颜色'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号（画布Y轴顺序）'),
    sa.Column('first_chapter', sa.Integer(), nullable=True, comment='首次出现章节'),
    sa.Column('latest_chapter', sa.Integer(), nullable=True, comment='最近出现章节'),
    sa.Column('event_count', sa.Integer(), nullable=True, comment='事件数'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='额外数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_lines_project_id'), 'story_lines', ['project_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False, comment='章节序号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='章节标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='章节内容'),
    sa.Column('summary', sa.Text(), nullable=True, comment='章节摘要'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='字数统计'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='章节状态'),
    sa.Column('outline_id', sa.String(length=36), nullable=True, comment='关联的大纲ID'),
    sa.Column('sub_index', sa.Integer(), nullable=True, comment='大纲下的子章节序号'),
    sa.Column('expansion_plan', sa.Text(), nullable=True, comment='展开规划详情(JSON): 包含key_events, character_focus, emotional_tone等'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_project', 'chapters', ['project_id'], unique=False)
    op.create_index('idx_chapter_project_number', 'chapters', ['project_id', 'chapter_number'], unique=False)
    op.create_index('idx_chapter_status', 'chapters', ['status'], unique=False)
    op.create_table('foreshadows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='伏笔标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='伏笔详细内容/描述'),
    sa.Column('hint_text', sa.Text(), nullable=True, comment='埋伏笔时的暗示文本(原文摘录或概述)'),
    sa.Column('resolution_text', sa.Text(), nullable=True, comment='回收伏笔时的揭示文本(原文摘录或概述)'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源类型: analysis=分析提取, manual=手动添加'),
    sa.Column('source_memory_id', sa.String(length=100), nullable=True, comment='来源记忆ID(如从分析结果同步)'),
    sa.Column('source_analysis_id', sa.String(length=36), nullable=True, comment='来源分析任务ID'),
    sa.Column('plant_chapter_id', sa.String(length=36), nullable=True, comment='埋入章节ID'),
    sa.Column('plant_chapter_number', sa.Integer(), nullable=True, comment='埋入章节号(冗余存储便于查询)'),
    sa.Column('target_resolve_chapter_id', sa.String(length=36), nullable=True, comment='计划回收章节ID'),
    sa.Column('target_resolve_chapter_number', sa.Integer(), nullable=True, comment='计划回收章节号'),
    sa.Column('actual_resolve_chapter_id', sa.String(length=36), nullable=True, comment='实际回收章节ID'),
    sa.Column('actual_resolve_chapter_number', sa.Integer(), nullable=True, comment='实际回收章节号'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='\n    伏笔状态:\n    - pending: 待埋入(已规划但未写入章节)\n    - planted: 已埋入(已在章节中埋下)\n    - resolved: 已回收(已在章节中回收)\n    - partially_resolved: 部分回收(长线伏笔可能分多次回收)\n    - abandoned: 已废弃(决定不再使用此伏笔)\n    '),
    sa.Column('is_long_term', sa.Boolean(), nullable=True, comment='是否长线伏笔(跨多章的重要伏笔)'),
    sa.Column('importance', sa.Float(), nullable=True, comment='重要性评分 0.0-1.0'),
    sa.Column('strength', sa.Integer(), nullable=True, comment='伏笔强度 1-10(影响读者多强烈)'),
    sa.Column('subtlety', sa.Integer(), nullable=True, comment='隐藏度 1-10(越高越隐蔽)'),
    sa.Column('urgency', sa.Integer(), nullable=True, comment='紧急度: 0=不紧急, 1=需关注, 2=急需回收'),
    sa.Column('related_characters', sa.JSON(), nullable=True, comment="关联角色名列表: ['角色1', '角色2']"),
    sa.Column('related_foreshadow_ids', sa.JSON(), nullable=True, comment='关联的其他伏笔ID列表(伏笔链)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment="标签列表: ['身世', '悬念', '反转']"),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类: identity(身世), mystery(悬念), item(物品), relationship(关系), event(事件)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='创作备注(仅作者可见)'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='回收方式说明'),
    sa.Column('auto_remind', sa.Boolean(), nullable=True, comment='是否在章节生成时自动提醒'),
    sa.Column('remind_before_chapters', sa.Integer(), nullable=True, comment='提前几章开始提醒回收'),
    sa.Column('include_in_context', sa.Boolean(), nullable=True, comment='是否包含在生成上下文中'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('planted_at', sa.DateTime(), nullable=True, comment='埋入时间'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='回收时间'),
    sa.ForeignKeyConstraint(['actual_resolve_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_resolve_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadows_project_id'), 'foreshadows', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadows_status'), 'foreshadows', ['status'], unique=False)
    op.create_table('plot_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('plot_stage', sa.String(length=50), nullable=True, comment='剧情阶段: 开端/发展/高潮/结局/过渡'),
    sa.Column('conflict_level', sa.Integer(), nullable=True, comment='冲突强度 1-10'),
    sa.Column('conflict_types', sa.JSON(), nullable=True, comment="冲突类型列表: ['人与人', '人与己', '人与环境']"),
    sa.Column('emotional_tone', sa.String(length=100), nullable=True, comment='主导情感: 紧张/温馨/悲伤/激昂/平静'),
    sa.Column('emotional_intensity', sa.Float(), nullable=True, comment='情感强度 0.0-1.0'),
    sa.Column('emotional_curve', sa.JSON(), nullable=True, comment='情感曲线: {start: 0.3, middle: 0.7, end: 0.5}'),
    sa.Column('hooks', sa.JSON(), nullable=True, comment='钩子列表 - 吸引读者的元素: [\n        {\n            "type": "悬念|情感|冲突|认知",\n            "content": "具体内容",\n            "strength": 8,\n            "position": "开头|中段|结尾"\n        }\n    ]'),
    sa.Column('hooks_count', sa.Integer(), nullable=True, comment='钩子数量'),
    sa.Column('hooks_avg_strength', sa.Float(), nullable=True, comment='钩子平均强度'),
    sa.Column('foreshadows', sa.JSON(), nullable=True, comment='伏笔列表: [\n        {\n            "content": "伏笔内容",\n            "type": "planted|resolved",\n            "strength": 7,\n            "subtlety": 8,\n            "reference_chapter": 3\n        }\n    ]'),
    sa.Column('foreshadows_planted', sa.Integer(), nullable=True, comment='本章埋下的伏笔数量'),
    sa.Column('foreshadows_resolved', sa.Integer(), nullable=True, comment='本章回收的伏笔数量'),
    sa.Column('plot_points', sa.JSON(), nullable=True, comment='情节点列表: [\n        {\n            "content": "情节点描述",\n            "importance": 0.9,\n            "type": "revelation|conflict|resolution|transition",\n            "impact": "对故事的影响描述"\n        }\n    ]'),
    sa.Column('plot_points_count', sa.Integer(), nullable=True, comment='情节点数量'),
    sa.Column('character_states', sa.JSON(), nullable=True, comment='角色状态变化: [\n        {\n            "character_id": "xxx",\n            "character_name": "张三",\n            "state_before": "犹豫不决",\n            "state_after": "坚定信念",\n            "psychological_change": "内心描述",\n            "key_event": "触发事件",\n            "relationship_changes": {"李四": "关系变化"}\n        }\n    ]'),
    sa.Column('scenes', sa.JSON(), nullable=True, comment="场景列表: [{location: '地点', atmosphere: '氛围', duration: '时长'}]"),
    sa.Column('pacing', sa.String(length=50), nullable=True, comment='节奏: slow|moderate|fast|varied'),
    sa.Column('overall_quality_score', sa.Float(), nullable=True, comment='整体质量评分 0.0-10.0'),
    sa.Column('pacing_score', sa.Float(), nullable=True, comment='节奏评分 0.0-10.0'),
    sa.Column('engagement_score', sa.Float(), nullable=True, comment='吸引力评分 0.0-10.0'),
    sa.Column('coherence_score', sa.Float(), nullable=True, comment='连贯性评分 0.0-10.0'),
    sa.Column('causal_density', sa.Float(), nullable=True, comment='因果链密度（每千字因果节点数）'),
    sa.Column('conflict_intensity', sa.Float(), nullable=True, comment='冲突烈度（0.0-1.0）'),
    sa.Column('foreshadow_density', sa.Float(), nullable=True, comment='伏笔密度（每千字新埋伏笔数）'),
    sa.Column('character_states_snapshot', sa.JSON(), nullable=True, comment='角色状态快照: [\n        {name, status, current_state, state_updated_chapter}\n    ]'),
    sa.Column('causal_links_snapshot', sa.JSON(), nullable=True, comment='因果链快照（影响本章的）: [\n        {cause_chapter, description, strength}\n    ]'),
    sa.Column('foreshadows_snapshot', sa.JSON(), nullable=True, comment='伏笔快照: [\n        {title, status, plant_chapter, target_resolve_chapter, actual_resolve_chapter}\n    ]'),
    sa.Column('storylines_snapshot', sa.JSON(), nullable=True, comment='故事线快照: [\n        {name, line_type, status, first_chapter, latest_chapter, event_count}\n    ]'),
    sa.Column('world_rules_snapshot', sa.JSON(), nullable=True, comment='世界观快照: {\n        rules_text, drift_detected, drift_details, world_states_summary, chapter\n    }'),
    sa.Column('event_chain_snapshot', sa.JSON(), nullable=True, comment='事件链快照: [\n        {event_id, event_type, title, description, chapter, tags}\n    ]'),
    sa.Column('analysis_report', sa.Text(), nullable=True, comment='完整的文字分析报告'),
    sa.Column('suggestions', sa.JSON(), nullable=True, comment="改进建议列表: ['建议1', '建议2']"),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='章节字数'),
    sa.Column('dialogue_ratio', sa.Float(), nullable=True, comment='对话占比 0.0-1.0'),
    sa.Column('description_ratio', sa.Float(), nullable=True, comment='描写占比 0.0-1.0'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='分析时间'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_analysis_chapter_id'), 'plot_analysis', ['chapter_id'], unique=True)
    op.create_index(op.f('ix_plot_analysis_project_id'), 'plot_analysis', ['project_id'], unique=False)
    op.create_table('pm_consistency_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False, comment='状态所属章节号'),
    sa.Column('character_states', sa.JSON(), nullable=False, comment='所有活跃角色的位置/情绪/能力等状态'),
    sa.Column('world_states', sa.JSON(), nullable=False, comment='世界观设定中处于变化中的状态'),
    sa.Column('foreshadow_status', sa.JSON(), nullable=False, comment='伏笔标题→状态的摘要映射'),
    sa.Column('character_arc_progress', sa.JSON(), nullable=False, comment='各角色当前所处的弧线阶段'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='快照创建时间'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_number', name='uq_pm_consistency_project_chapter')
    )
    op.create_index(op.f('ix_pm_consistency_state_project_id'), 'pm_consistency_state', ['project_id'], unique=False)
    op.create_table('story_memories',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False, comment='\n    记忆类型:\n    - plot_point: 情节点\n    - character_event: 角色事件\n    - world_detail: 世界观细节\n    - hook: 钩子(悬念/冲突)\n    - foreshadow: 伏笔\n    - dialogue: 重要对话\n    - scene: 场景描写\n    '),
    sa.Column('title', sa.String(length=200), nullable=True, comment='记忆标题/简述'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆内容摘要(100-500字)'),
    sa.Column('full_context', sa.Text(), nullable=True, comment='完整上下文(可选,用于详细记录)'),
    sa.Column('related_characters', sa.JSON(), nullable=True, comment="涉及角色ID列表: ['char_id_1', 'char_id_2']"),
    sa.Column('related_locations', sa.JSON(), nullable=True, comment="涉及地点列表: ['地点1', '地点2']"),
    sa.Column('tags', sa.JSON(), nullable=True, comment="标签列表: ['悬念', '转折', '伏笔', '高潮']"),
    sa.Column('importance_score', sa.Float(), nullable=True, comment='重要性评分 0.0-1.0'),
    sa.Column('story_timeline', sa.Integer(), nullable=False, comment='故事时间线位置(章节序号)'),
    sa.Column('chapter_position', sa.Integer(), nullable=True, comment='章节内位置(字符位置)'),
    sa.Column('text_length', sa.Integer(), nullable=True, comment='文本长度(字符数)'),
    sa.Column('is_foreshadow', sa.Integer(), nullable=True, comment='伏笔状态: 0=普通记忆, 1=已埋下伏笔, 2=伏笔已回收'),
    sa.Column('foreshadow_resolved_at', sa.String(length=100), nullable=True, comment='伏笔回收的章节ID'),
    sa.Column('foreshadow_strength', sa.Float(), nullable=True, comment='伏笔强度 0.0-1.0'),
    sa.Column('vector_id', sa.String(length=100), nullable=True, comment='向量数据库中的唯一ID'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='使用的embedding模型'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foreshadow_resolved_at'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_id')
    )
    op.create_index(op.f('ix_story_memories_chapter_id'), 'story_memories', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_story_memories_memory_type'), 'story_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_story_memories_project_id'), 'story_memories', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_memories_story_timeline'), 'story_memories', ['story_timeline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_memories_story_timeline'), table_name='story_memories')
    op.drop_index(op.f('ix_story_memories_project_id'), table_name='story_memories')
    op.drop_index(op.f('ix_story_memories_memory_type'), table_name='story_memories')
    op.drop_index(op.f('ix_story_memories_chapter_id'), table_name='story_memories')
    op.drop_table('story_memories')
    op.drop_index(op.f('ix_pm_consistency_state_project_id'), table_name='pm_consistency_state')
    op.drop_table('pm_consistency_state')
    op.drop_index(op.f('ix_plot_analysis_project_id'), table_name='plot_analysis')
    op.drop_index(op.f('ix_plot_analysis_chapter_id'), table_name='plot_analysis')
    op.drop_table('plot_analysis')
    op.drop_index(op.f('ix_foreshadows_status'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_project_id'), table_name='foreshadows')
    op.drop_table('foreshadows')
    op.drop_index('idx_chapter_status', table_name='chapters')
    op.drop_index('idx_chapter_project_number', table_name='chapters')
    op.drop_index('idx_chapter_project', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_story_lines_project_id'), table_name='story_lines')
    op.drop_table('story_lines')
    op.drop_table('skills')
    op.drop_index(op.f('ix_pm_session_summaries_session_id'), table_name='pm_session_summaries')
    op.drop_index(op.f('ix_pm_session_summaries_project_id'), table_name='pm_session_summaries')
    op.drop_table('pm_session_summaries')
    op.drop_index('idx_outline_project', table_name='outlines')
    op.drop_table('outlines')
    op.drop_index('ix_ooc_violations_project_status', table_name='ooc_violations')
    op.drop_index(op.f('ix_ooc_violations_project_id'), table_name='ooc_violations')
    op.drop_index(op.f('ix_ooc_violations_created_at'), table_name='ooc_violations')
    op.drop_index(op.f('ix_ooc_violations_character_id'), table_name='ooc_violations')
    op.drop_index(op.f('ix_ooc_violations_chapter_id'), table_name='ooc_violations')
    op.drop_table('ooc_violations')
    op.drop_index('idx_character_role', table_name='characters')
    op.drop_index('idx_character_project', table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_character_relationships_project_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_to_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_from_id'), table_name='character_relationships')
    op.drop_index('ix_char_rels_from_to', table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_index('idx_user_id', table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pm_user_profiles_user_id'), table_name='pm_user_profiles')
    op.drop_table('pm_user_profiles')
    op.drop_index(op.f('ix_pm_user_preferences_user_id'), table_name='pm_user_preferences')
    op.drop_index(op.f('ix_pm_user_preferences_project_id'), table_name='pm_user_preferences')
    op.drop_table('pm_user_preferences')
    op.drop_index(op.f('ix_pm_token_usage_user_id'), table_name='pm_token_usage')
    op.drop_index(op.f('ix_pm_token_usage_project_id'), table_name='pm_token_usage')
    op.drop_index(op.f('ix_pm_token_usage_created_at'), table_name='pm_token_usage')
    op.drop_index('idx_pm_token_user_created', table_name='pm_token_usage')
    op.drop_index('idx_pm_token_project_created', table_name='pm_token_usage')
    op.drop_table('pm_token_usage')
    op.drop_index(op.f('ix_pm_session_state_user_id'), table_name='pm_session_state')
    op.drop_index(op.f('ix_pm_session_state_project_id'), table_name='pm_session_state')
    op.drop_table('pm_session_state')
    op.drop_table('pm_leader_lock')
    op.drop_index(op.f('ix_pm_history_patterns_user_id'), table_name='pm_history_patterns')
    op.drop_index(op.f('ix_pm_history_patterns_project_id'), table_name='pm_history_patterns')
    op.drop_table('pm_history_patterns')
    op.drop_index(op.f('ix_pm_guidance_feedback_decision_log_id'), table_name='pm_guidance_feedback')
    op.drop_index('idx_guidance_fb_type_created', table_name='pm_guidance_feedback')
    op.drop_table('pm_guidance_feedback')
    op.drop_index(op.f('ix_pm_goal_tree_user_id'), table_name='pm_goal_tree')
    op.drop_index(op.f('ix_pm_goal_tree_project_id'), table_name='pm_goal_tree')
    op.drop_index(op.f('ix_pm_goal_tree_parent_id'), table_name='pm_goal_tree')
    op.drop_index(op.f('ix_pm_goal_tree_goal_id'), table_name='pm_goal_tree')
    op.drop_table('pm_goal_tree')
    op.drop_index(op.f('ix_pm_fix_patterns_issue_type'), table_name='pm_fix_patterns')
    op.drop_index('idx_fix_pattern_type_created', table_name='pm_fix_patterns')
    op.drop_table('pm_fix_patterns')
    op.drop_index(op.f('ix_pm_failure_patterns_project_id'), table_name='pm_failure_patterns')
    op.drop_table('pm_failure_patterns')
    op.drop_index(op.f('ix_pm_experience_cards_project_id'), table_name='pm_experience_cards')
    op.drop_table('pm_experience_cards')
    op.drop_index(op.f('ix_pm_diagnostic_logs_user_id'), table_name='pm_diagnostic_logs')
    op.drop_index(op.f('ix_pm_diagnostic_logs_resolved'), table_name='pm_diagnostic_logs')
    op.drop_index(op.f('ix_pm_diagnostic_logs_project_id'), table_name='pm_diagnostic_logs')
    op.drop_index(op.f('ix_pm_diagnostic_logs_diag_type'), table_name='pm_diagnostic_logs')
    op.drop_index('idx_diag_user', table_name='pm_diagnostic_logs')
    op.drop_index('idx_diag_type', table_name='pm_diagnostic_logs')
    op.drop_index('idx_diag_resolved', table_name='pm_diagnostic_logs')
    op.drop_index('idx_diag_project', table_name='pm_diagnostic_logs')
    op.drop_table('pm_diagnostic_logs')
    op.drop_index(op.f('ix_pm_decision_log_user_id'), table_name='pm_decision_log')
    op.drop_index(op.f('ix_pm_decision_log_project_id'), table_name='pm_decision_log')
    op.drop_index(op.f('ix_pm_decision_log_created_at'), table_name='pm_decision_log')
    op.drop_index('idx_pm_decision_resolved', table_name='pm_decision_log')
    op.drop_index('idx_pm_decision_project_created', table_name='pm_decision_log')
    op.drop_table('pm_decision_log')
    op.drop_index(op.f('ix_pm_autonomy_config_user_id'), table_name='pm_autonomy_config')
    op.drop_index(op.f('ix_pm_autonomy_config_project_id'), table_name='pm_autonomy_config')
    op.drop_table('pm_autonomy_config')
    op.drop_index(op.f('ix_pm_action_log_user_id'), table_name='pm_action_log')
    op.drop_index(op.f('ix_pm_action_log_tool_name'), table_name='pm_action_log')
    op.drop_index(op.f('ix_pm_action_log_project_id'), table_name='pm_action_log')
    op.drop_table('pm_action_log')
    op.drop_index(op.f('ix_narrative_structure_nodes_project_id'), table_name='narrative_structure_nodes')
    op.drop_table('narrative_structure_nodes')
    op.drop_index(op.f('ix_mistake_logs_user_id'), table_name='mistake_logs')
    op.drop_index(op.f('ix_mistake_logs_project_id'), table_name='mistake_logs')
    op.drop_index(op.f('ix_mistake_logs_error_type'), table_name='mistake_logs')
    op.drop_index(op.f('ix_mistake_logs_command_name'), table_name='mistake_logs')
    op.drop_table('mistake_logs')
    op.drop_index(op.f('ix_golden_fingers_project_id'), table_name='golden_fingers')
    op.drop_table('golden_fingers')
    op.drop_index(op.f('ix_goal_stability_log_project_id'), table_name='goal_stability_log')
    op.drop_index(op.f('ix_goal_stability_log_goal_id'), table_name='goal_stability_log')
    op.drop_table('goal_stability_log')
    op.drop_index(op.f('ix_analysis_tasks_user_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_project_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_created_at'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_chapter_id'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    # ### end Alembic commands ###
